openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  description: ""
  contact:
    email: wichmann@bbs-os-brinkstr.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
- url: http://127.0.0.1:5000/
tags:
- name: Listenverwaltung
paths:
  # endpoints dealing with entire todo lists
  /todo-list/{list_id}:
    get:
      tags:
      - Listenverwaltung
      summary: Liefert alle Einträge einer Todo-Liste zurück
      operationId: getList
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Erfolgreicher Abruf
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        '404':
          description: Fehlerhafte ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
      - Listenverwaltung
      summary: Löscht eine komplette Todo-Liste mit allen Einträgen
      operationId: deleteList
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Erfolgreiches Löschen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Fehlerhafte ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  # Create new list
  /todo-list:
    post:
      tags:
      - Listenverwaltung
      summary: Fügt eine neue Todo-Liste hinzu
      operationId: addList
      requestBody:
        description: Neues Listenobjekt
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        '201':
          description: Erfolgreiches Anlegen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '406':
          description: Fehlerhafte Daten im Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-codegen-request-body-name: body
  # Add entry to existing list
  /todo-list/{list_id}:
    post:
      tags:
      - Listenverwaltung
      summary: Fügt einen Eintrag zu einer bestehenden Todo-Liste hinzu
      operationId: addEntryToList
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      requestBody:
        description: Objekt des neuen Eintrags
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                description:
                  type: string
            example:
              name: "Beispielname"
              description: "Kurzbeschreibung"
      responses:
        '201':
          description: Erfolgreiches Anlegen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        '404':
          description: Fehlerhafte ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '406':
          description: Fehlerhafte Daten im Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  # endpoints for individual entries
  /entry/{entry_id}:
    patch:
      tags:
      - Listenverwaltung
      summary: Aktualisiert einen bestehenden Eintrag
      operationId: updateEntry
      parameters:
      - name: entry_id
        in: path
        description: ID des gewünschten Eintrags
        required: true
        schema:
          type: string
      requestBody:
        description: Nur die zu ändernden Felder
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Erfolgreiches Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        '404':
          description: Fehlerhafte ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '406':
          description: Fehlerhafte Daten im Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags:
      - Listenverwaltung
      summary: Löscht einen einzelnen Eintrag einer Todo-Liste
      operationId: deleteEntry
      parameters:
      - name: entry_id
        in: path
        description: ID des gewünschten Eintrags
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Erfolgreiches Löschen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Fehlerhafte ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server-Fehler
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        user_id:
          type: string
          format: uuid
        list_id:
          type: string
          format: uuid
